[package]
name = "advent-of-code-2018"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.13"
regex = "1"
chrono = "0.4.6"
lazy_static = "1.2.0"
rayon = "1.0.3"
itertools = "0.8.0"
aoc-tools = { path="aoc-tools" }