[package]
name = "aoc-tools"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"

[dependencies]
aoc-tools-macros = { path = "aoc-tools-macros" }
lazy_static = "1.0"
regex = "1.0"
