[package]
name = "aoc-solutions"
version = "0.1.0"
authors = ["Felix Kohlgrüber <felix.kohlgrueber@gmail.com>"]
edition = "2018"
build = "build.rs"


[lib]
path = "lib.rs"

[dependencies]
aoc-tools = { path = "../aoc-tools" }
lazy_static = "1.2.0"